export var projectPath = {
    "common":{
        "path":"/generate/src/app/common",
        "_components":{
            "path":"/generate/src/app/common/_components"
        },
        "_directives":{
            "path":"/generate/src/app/common/_directives"
        },
        "_interfaces":{
            "path":"/generate/src/app/common/_interfaces"
        },
        "_consts":{
            "path":"/generate/src/app/common/_consts"
        },
        "_functions":{
            "path":"/generate/src/app/common/_functions"
        },
        "_modules":{
            "path":"/generate/src/app/common/_modules"
        },
        "_pipes":{
            "path":"/generate/src/app/common/_pipes"
        },
        "_services":{
            "path":"/generate/src/app/common/_services"
        }
    },
    "main":{
        "path":"/generate/src/app/main"
    },
    "assets":{
        "path":"/generate/src/assets",
        "partials":{
            "path":"/generate/src/assets/partials",
            "_base":{
                "path":"/generate/src/assets/partials/_base",
            },
            "_modules":{
                "path":"/generate/src/assets/partials/_modules",
                "_components":{
                    "path":"/generate/src/assets/partials/_modules/_components",
                }
            },
            "_layouts":{
                "path":"/generate/src/assets/partials/_layouts",
            },
            "_utils":{
                "path":"/generate/src/assets/partials/_utils",
                "_mixins":{
                    "path":"/generate/src/assets/partials/_modules/_mixins",
                }
            },
        },
        "images":{
            "path":"/generate/src/assets/images",
        }
    },
    "environment":{
        "path":"/generate/src/environments"
    }
    
}